### PR TITLE
Upgrade CSS into Sass 

### PR DESCRIPTION
**Pull request by ajwl**
Clean up project by putting CSS into Sass. 

Work in Progress

### CODE REVIEW

**Comment by ajwl** [comment]
@ClaudiaHosu - can you see why I might be getting this Java error? 

screen shot 2016-08-08 at 08 32 55

**Comment by ajwl** [comment]
Pfh - and now this one. Any ideas? 

```
HTTP Status 500 - /pages/products.jsp (line: 103, column: 1) File [shared/_footer.jsp] not found

type Exception report

message /pages/products.jsp (line: 103, column: 1) File [shared/_footer.jsp] not found

description The server encountered an internal error that prevented it from fulfilling this request.

exception

org.apache.jasper.JasperException: /pages/products.jsp (line: 103, column: 1) File [shared/_footer.jsp] not found
    org.apache.jasper.compiler.DefaultErrorHandler.jspError(DefaultErrorHandler.java:41)
    org.apache.jasper.compiler.ErrorDispatcher.dispatch(ErrorDispatcher.java:275)
    org.apache.jasper.compiler.ErrorDispatcher.jspError(ErrorDispatcher.java:91)
    org.apache.jasper.compiler.Parser.processIncludeDirective(Parser.java:333)
    org.apache.jasper.compiler.Parser.parseIncludeDirective(Parser.java:368)
    org.apache.jasper.compiler.Parser.parseDirective(Parser.java:471)
```

@ClaudiaHosu

**Comment by ClaudiaHosu** [comment]
Can you bring your laptop today and we can have a look? Seems like it can't
find these pages.

Claudia

**Comment by ajwl** [comment]
Cool – yes I will do

**Pull request closed without merging**
